frontend_homepage:
    pattern:  /
    defaults: { _controller: MainPageFrontendBundle:Default:index }
frontend_about:
    pattern:  /about
    defaults: { _controller: MainPageFrontendBundle:Default:about }
frontend_translations:
    pattern:  /translations
    defaults: { _controller: MainPageFrontendBundle:Default:translations }
frontend_online:
    pattern:  /online-courses
    defaults: { _controller: MainPageFrontendBundle:Default:online }
frontend_lessons:
    pattern:  /lessons-and-translations
    defaults: { _controller: MainPageFrontendBundle:Default:lessons }
frontend_contact:
    pattern:  /contact
    defaults: { _controller: MainPageFrontendBundle:Default:contact }

email_form:
    pattern:  /contact/form
    defaults: { _controller: MainPageFrontendBundle:Default:email }
  