parameters:
#    main_page_frontend.example.class: Main\Page\FrontendBundle\Example

services:
#    main_page_frontend.example:
#        class: %main_page_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
